version: "3"
services:
  pyone:
    image: setzero/pyone
    restart: always
    ports:
    - "80:80"
    # - "2222:22"
    environment:
    - TZ=Asia/Shanghai
    - PORT=34567
    # - SSH_PASSWORD=root
    # - DISABLE_REFRESH_CACHE=true
    - REFRESH_CACHE_ALL=0 3 */1 * *
    - REFRESH_CACHE_NEW=*/15 * * * *
    volumes:
    - ./pyone/data:/data
    - ./pyone/PyOne:/root/PyOne